
# Model arguments
model_name_or_path: DAMO-NLP-MT/polylm-13b-fine-grained-shards
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- c_attn

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  airesearch/concat_six_dataset_th_en : 1.0
dataset_splits:
- train
preprocessing_num_workers: 12


# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: 'no'
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-04
log_level: info
logging_steps: 70
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 6
output_dir: data/polylm-13b-sft-qlora
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
report_to:
- wandb
save_strategy: "steps"
save_steps: 1000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1